### ISSUE TITLE
generateTrips() should use full route_type list

### ISSUE THREAD

**Issue by nickolasclarke** [nickolasclarke/dispatch#46]
Generate trips only builds for `route_type = 3` https://github.com/nickolasclarke/dispatch/blob/78cdd6855c8cfdde63fd17af053d108827e26df6/src/parse_gtfs.py#L153

It should use the route_types outlined in 
https://github.com/nickolasclarke/dispatch/blob/78cdd6855c8cfdde63fd17af053d108827e26df6/src/parse_gtfs.py#L339

**Comment by r-barnes** [comment]
Fixed.
